baseURL = "https://podracing.net/"
defaultContentLanguage = "en"
theme = "hermit"
 
languageCode = "en-us"

title = "go away"

disableKinds = ["page", "section", "taxonomy", "term", "rss", "sitemap", "robotstxt"]

[params.author]
  name = "Site Admin"

[params]
  themeColor = "#494f5c"

  homeSubtitle = "-- podracing.net --"
  footerCopyright = "COPYLEFT"
  
  justifyContent = false
  shareSocial = true

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/klownzilla"
