baseURL = "https://podracing.net/"
languageCode = "en-us"
theme = "hermit-v2"

defaultContentLanguage = "en"
title = "-- podracing.net --"

disableKinds = ["page", "section", "taxonomy", "term", "rss", "sitemap", "robotstxt"]

[params.author]
  name = "kzilla"

[params]
  description = "A small site..."
  themeColor = "#282a36"

  homeSubtitle = "-- podracing.net --"
  footerCopyright = "COPYLEFT"
  
  justifyContent = false
  shareSocial = false
  code_copy_button = false

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/klownzilla"

  [[params.socialLinks]]
    name = "email"
    url = "kzilla@podracing.net"
